### Отправка данных студента
POST localhost:8075/formstudent
Content-Type: application/json

{
  "tgId": "320238701",
  "Name": "1",
  "birthday": "30.05.2004",
  "city": "1",
  "skill": [
    "Написание текстов",
    "Написание текстов"
  ],
  "email": "1"
}

### Отправка данных компании
POST localhost:8075/formbusiness
Content-Type: application/json

{
  "tgId": "1098511932",
  "CompanyName": "123",
  "INN": "123",
  "FieldOfActivity": "Финансы / бухгалтерия",
  "ContactPersonFullName": "123",
  "ContactPersonPhone": "123"
}

### Отправка данных при создании лота
POST localhost:8075/formlot
Content-Type: application/json

{
  "tgId":"1098511932",
  "nameTask":"Название",
  "direction": "Направление задач",
  "description":"123",
  "IMG":["14iNJPXyMRXemoHCBS7vjwegTyZO89GB0"],
  "Link":"https://docs.google.com/forms/d/e/1FAIpQLScQgB6T74K87rZHi8a9qi-l565V3rrO5sKUlHe9LStZiRM3YA/",
  "deadline":"345",
  "slotCall":"345"
}
