### Отправка данных о изменение задачи
POST localhost:8075/yougile
Content-Type: application/json

{
  "event": "task-updated",
  "payload": {
    "title": "название",
    "timestamp": 1748264333564,
    "columnId": "5bfcc202-886a-4457-b037-15f8d5604558",
    "description": "\n\tБюджет:123123\n\tОписание:описание\n",
    "archived": false,
    "completed": false,
    "assigned": [
      "974996c7-0c98-494f-90c0-a246f449ab16"
    ],
    "createdBy": "974996c7-0c98-494f-90c0-a246f449ab16",
    "deadline": {
      "deadline": 1744416000000,
      "history": [
        {
          "deadline": 1744416000000,
          "timestamp": 1748264333572,
          "by": "974996c7-0c98-494f-90c0-a246f449ab16"
        }
      ]
    },
    "id": "1ff29ec3-81cb-4960-a045-b580d6670f49",
    "parents": []
  },
  "prevData": {
    "title": "название",
    "timestamp": 1748264333564,
    "columnId": "5bfcc202-886a-4457-b037-15f8d5604558",
    "description": "\n\tБюджет:123123\n\tОписание:описание\n",
    "archived": false,
    "completed": false,
    "createdBy": "974996c7-0c98-494f-90c0-a246f449ab16",
    "deadline": {
      "deadline": 1744416000000,
      "history": [
        {
          "deadline": 1744416000000,
          "timestamp": 1748264333572,
          "by": "974996c7-0c98-494f-90c0-a246f449ab16"
        }
      ]
    },
    "id": "1ff29ec3-81cb-4960-a045-b580d6670f49",
    "parents": []
  },
  "fromUserId": "974996c7-0c98-494f-90c0-a246f449ab16"
}

### Отправка данных о перестановке задачи в блок "В работе"
POST localhost:8075/yougile
Content-Type: application/json


{
  "event": "task-moved",
  "payload": {
    "title": "название",
    "timestamp": 1747869679889,
    "columnId": "ab3e05ea-9092-478f-a4f6-e88b204c8408",
    "description": "описание",
    "archived": false,
    "completed": false,
    "assigned": [
      "974996c7-0c98-494f-90c0-a246f449ab16"
    ],
    "createdBy": "974996c7-0c98-494f-90c0-a246f449ab16",
    "id": "1ff29ec3-81cb-4960-a045-b580d6670f49",
    "parents": []
  },
  "prevData": {
    "title": "название",
    "timestamp": 1747869679889,
    "columnId": "5bfcc202-886a-4457-b037-15f8d5604558",
    "description": "описание",
    "archived": false,
    "completed": false,
    "assigned": [
      "974996c7-0c98-494f-90c0-a246f449ab16"
    ],
    "createdBy": "974996c7-0c98-494f-90c0-a246f449ab16",
    "id": "1ff29ec3-81cb-4960-a045-b580d6670f49",
    "parents": []
  },
  "fromUserId": "974996c7-0c98-494f-90c0-a246f449ab16"
}