### Отправка данных студента
POST localhost:8075/formstudent
Content-Type: application/json

{
  "tgId": "1098511932",
  "Name": "Данила Глазатов",
  "birthday": "30.05.2004",
  "city": "Санкт-Петербург",
  "skill": [
    "Написание текстов"
  ],
  "email": "impressia.nn@gmail.com"
}

### Отправка данных компании
POST localhost:8075/formbusiness
Content-Type: application/json

{
  "tgId": "1098511932",
  "CompanyName": "123",
  "INN": "123",
  "FieldOfActivity": "Финансы / бухгалтерия",
  "ContactPersonFullName": "123",
  "ContactPersonPhone": "123"
}

### Отправка данных при создании задачи
POST localhost:8075/formlot
Content-Type: application/json

{
  "tgId": "1098511932",
  "nameTask": "Тест",
  "description": "описание",
  "budget": "123123",
  "direction": "Подготовка презентаций",
  "Link": "",
  "deadline": "12.04.2025",
  "slotCall": "12.04.2025"
}
